# -*- coding: utf-8 -*-
"""Otp_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZ_yfGZi4TPLWxUwRp-ElhMnWeOV-5_i
"""

import random

def generate_otp( ):
    try:
        otp = ''
        for i in range(6):
            otp += str(random.randint(0, 9))
        return otp
    except Exception as e:
        print(f"Error generating OTP: {e}")
        return None

if __name__ == "__main__":
    try:
        # Generate OTP
        otp = generate_otp()

        if otp:
            # Display OTP
            print(f"valid OTP: {otp}")
        else:
            print("Invalid Otp.")

    except Exception as e:
        print(f"Error: {e}")